# Generated by Django 2.2.4 on 2020-02-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
